ci: Add checks for versions and license headers

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -229,6 +229,40 @@ jobs:
       - name: Test Docker image
         run: make test-docker
 
+  check-license-header:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Run license check
+        run: make license-header
+
+      - name: Check for changes
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "ERROR: License headers missing or obsolete.\nTo fix, run 'make license-header' and git commit the changes."
+            exit 1
+          else
+            echo "License headers up-to-date."
+
+  check-version:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Run version check
+        run: make version
+
+      - name: Check for changes
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "ERROR: Misaligned versions.\nTo fix, run 'make version' and git commit the changes."
+            exit 1
+          else
+            echo "Versions up-to-date."
+
   run-tests:
     runs-on: ubuntu-latest
     needs: [build-telepact-ts, build-telepact-java, build-telepact-py, build-telepact-cli]
